
package model.visitor;

public interface CommandVisitor extends ArtikelCommandVisitor,ArtikelManagerCommandVisitor,BestellungCommandVisitor,EinkaufsManagerCommandVisitor,KontoCommandVisitor,LieferartCommandVisitor,PositionInBestellungCommandVisitor,ProduktKatalogCommandVisitor,ServiceRegisterCommandVisitor,SuchManagerCommandVisitor,WarenlagerCommandVisitor{
    
    
}
